### ISSUE TITLE
Playervaults removing enchantments from all items

### ISSUE THREAD

**Issue by VoxaDub** [drtshock/PlayerVaults#144]
ERROR: http://hastebin.com/udoyukibak.sm
VERSIONS: http://i.imgur.com/qG1OGDA.png
When anyone puts enchanted items in their playervault and then proceeds to relog it removes all the enchantments from their vault and when I use the admin command to check their playervault is shows they do not even have any vaults

**Comment by drtshock** [comment]
Looks like it's because we're serializing against bukkit and not spigot. Should be fixed by just compiling against the latter.

**Comment by VoxaDub** [comment]
My friend already compiled it for spigot and the same error is still occuring

**Comment by drtshock** [comment]
Can you give me the new stack trace and show me the pom?

**Comment by VoxaDub** [comment]
http://hastebin.com/ejanilitog.sm
https://github.com/drtshock/PlayerVaults/blob/master/pom.xml

**Comment by drtshock** [comment]
lol? I meant the pom of you compiling against spigot.

**Comment by VoxaDub** [comment]
where do I get that? thats what my friend linked me

**Comment by drtshock** [comment]
then he didn't compile against spigot

**Comment by VoxaDub** [comment]
had someone else actually compile it against spigot and its still broken 
http://hastebin.com/hapigicimi.sm
https://gist.github.com/Ichbinjoe/6b3befb99f32794a172f

**Comment by drtshock** [comment]
You should update, this has been fixed.
