### ISSUE TITLE
Somes players can't open vault!

### ISSUE THREAD

**Issue by tuanjr** [drtshock/PlayerVaults#163]
after update server and restart, this error appear, and somes players (not all players in server) can't open their vault! Please fix it ASAP!
http://paste.ubuntu.com/15727935/

**Comment by SmallSansSerif** [comment]
Yeah this is happening on my server too.

**Comment by Televex** [comment]
That problem should've been fixed with this commit:
https://github.com/drtshock/PlayerVaults/commit/06bb39d345c1daa5460feea336459e7e06091ebf

**Comment by drtshock** [comment]
update

**Comment by tuanjr** [comment]
@drtshock forgive me but update what?
Current i use PlayerVault build 195 (lastest version) and Paperclip (paperspigot) lastest version, and someplayer still can't open vault.
