### ISSUE TITLE
sometime this error appear in console

### ISSUE THREAD

**Issue by tuanjr** [drtshock/PlayerVaults#191]
Player Vault buid 202 run in PaperSpigot 1.9.2
> [13:27:04] [Server thread/INFO]: toilatoi324 issued server command: /pv 1
[13:27:04] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pv' in plugin PlayerVaults v3.6.0-SNAPSHOT-b202
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:596) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.command.FormattedCommandAlias.execute(FormattedCommandAlias.java:41) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.9.2.jar:git-Paper-727]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:664) ~[patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1388) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1193) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.2.jar:git-Paper-727]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:813) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.2.jar:git-Paper-727]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.2.jar:git-Paper-727]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

**Comment by drtshock** [comment]
Can you please paste the full stack trace using a paste service like pastebin

**Comment by tuanjr** [comment]
I will give you full log in tomorrow,  when i on pc.

**Comment by tuanjr** [comment]
this is error: http://paste.ubuntu.com/17334373/

**Comment by drtshock** [comment]
Update. this should be fixed.

**Comment by tuanjr** [comment]
This still appear in Latest versions, build 203: http://paste.ubuntu.com/17353453/

**Comment by drtshock** [comment]
That's a different error and an incomplete stack trace. Please make a new ticket with the full one.
