### ISSUE TITLE
Internal Error occurred

### ISSUE THREAD

**Issue by jordanwilliams1** [drtshock/PlayerVaults#274]
One of my players can open a playe vault, They get "Internal Error occurred". There username is jkbuilder1110. I'm running on the latest spigot/playervualt build and no matter what he cant open a vault. I've tried a stand alone server with just playervaults but as soon as i do  /pv e7a17cf3-df79-46dd-97db-d52d695244d3 1. it gives me a Internal Error occurred

https://mcuuid.net/?q=e7a17cf3-df79-46dd-97db-d52d695244d3

Error:
https://www.hastebin.com/vadadufumo.vbs

**Comment by drtshock** [comment]
Update to build 210. Should be fixed in that.

**Comment by jordanwilliams1** [comment]
@drtshock As stated it was tested with the latest build. So it's still a problem :( 

I Just re-tested it and its still a problem:

Error:
https://hastebin.com/esepetawuk.vbs

Used this build:
https://ci.drtshock.net/job/PlayerVaults/210/
