### ISSUE TITLE
java.lang.NoSuchFieldError: LOCALE

### ISSUE THREAD

**Issue by Vitoldik** [drtshock/PlayerVaults#438]
[01:03:03] [Server thread/ERROR]: Error occurred while enabling PlayerVaults v4.2.0 (Is it up to date?)
java.lang.NoSuchFieldError: LOCALE
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.bukkit.BukkitAudience.contributePointers(BukkitAudience.java:117) ~[?:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.facet.FacetAudience.pointers(FacetAudience.java:449) ~[?:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.pointer.Pointered.getOrDefault(Pointered.java:65) ~[?:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:114) ~[?:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:100) ~[?:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:168) ~[?:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[?:1.8.0_251]
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2674) ~[?:1.8.0_251]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:168) ~[?:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89) ~[?:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
	at com.drtshock.playervaults.PlayerVaults.onEnable(PlayerVaults.java:120) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-655]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]

**Comment by mbax** [comment]
Can you reach out to me on Discord? https://discord.gg/JZcWDEt

**Comment by andrewkm** [comment]
@mbax
Same here

```
[23:19:15] [Server thread/ERROR]: Error occurred while enabling PlayerVaults v4.2.3 (Is it up to date?)
java.lang.NoSuchFieldError: LOCALE
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.bukkit.BukkitAudience.contributePointers(BukkitAudience.java:117) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.facet.FacetAudience.pointers(FacetAudience.java:449) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.pointer.Pointered.getOrDefault(Pointered.java:65) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:114) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:100) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:168) ~[PlayerVaultsX.jar:?]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1224) ~[?:?]
	at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2722) ~[?:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:168) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.lib.net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[PlayerVaultsX.jar:?]
	at com.drtshock.playervaults.PlayerVaults.onEnable(PlayerVaults.java:120) ~[PlayerVaultsX.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-278]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-278]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-278]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Paper-278]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-278]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-278]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by mbax** [comment]
Resolved with andrew, and lack of response from other reporter. Appears to work just fine when grabbed from spigot resources.

**Comment by Baterka** [comment]
Problem still persist. I bought it from Spigot resources but it would be fine to be able to build it and edit it for myself. Thx :)

**Comment by andrewkm** [comment]
Lol what? Do you English?

**Comment by Baterka** [comment]
> Lol what? Do you English?

Lol what? Do you read?
